### PR TITLE
Fix insertion of the core folder into python sys.path

### PR DESCRIPTION
**Pull request by evandrocoan**
Issue: https://github.com/hktonylee/SublimeNumberKing/issues/4

### CODE REVIEW

**Comment by hktonylee** [comment]
Hi @evandrocoan thanks for your contribution! However I do not use Sublime anymore. If you confirm that the fix is working, I will merge it without any check :-)

**Comment by evandrocoan** [comment]
It seems to be working, but I did not tests it thoroughly. You can wait a few months while I use it, perhaps I find something.

**Comment by bekicot** [comment]
Been a while @evandrocoan :), how is it?

**Comment by evandrocoan** [comment]
After a year and a few days I did not used much this plugin, but so far no errors on my console coming from this application.

**Comment by hktonylee** [comment]
@evandrocoan I have been waiting for your message for 1 year 🤣 Since there is no error I guess it is good enough to merge. Thanks again for your commit.

@bekicot If you find the CR doesn't work, please tell me and I will revert it.

**Pull request merged**
